export const ACTIONS = {
    GET_VIDEO_ACTION: 'GET_VIDEO_ACTION',
    GET_VIDEO_DATA_SUCCESS: 'GET_VIDEO_DATA_SUCCESS',
    SEARCH_VIDEO_ACTION: 'SEARCH_VIDEO_ACTION',
    SEARCH_VIDEO_FROM_SERVER_ACTION: 'SEARCH_VIDEO_FROM_SERVER_ACTION',
    SEARCH_VIDEO_SUCCESS_ACTION: 'SEARCH_VIDEO_SUCCESS_ACTION',
    CLEAR_VIDEO_ACTION: 'CLEAR_VIDEO_ACTION'
}
